spring.application.name=ServiceRegistryServer

eureka.instance.hostname=localhost

# khud ko register na kare
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

server.port=8761