spring.application.name=ServiceRegistryServer
server.port=8761
eureka.instance.hostname=localhost

# khud ko register na kare
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

